In [1]:
import quick_spice_manager

In [2]:
from quick_spice_manager.spice_manager import QuickSpiceManager

man = QuickSpiceManager()
tc = man.tour_config

man.load_kernels()

man.config

/tmp/ipykernel_320377/2531900779.py:4: DeprecationWarning: QuickSpiceManager.tour_config (property) is deprecated and will be removed in a future release. Use get_tour_config() instead.
  tc = man.tour_config

                                                         value
key
spacecraft                                               JUICE
version                                                 latest
metakernel   /data/.cache/quick-spice-manager/kernels/juice...
kernels_dir     /data/.cache/quick-spice-manager/kernels/juice

In [3]:
traj = tc["2025-01-01T00:00:00":"2026-01-01T00:00:00":'1 day']

traj.angular_size('callisto')

array([0.00038054, 0.00037917, 0.0003778 , 0.00037639, 0.0003749 ,
       0.00037329, 0.00037157, 0.00036973, 0.0003678 , 0.00036581,
       0.00036382, 0.00036188, 0.00036002, 0.00035829, 0.0003567 ,
       0.00035524, 0.00035392, 0.00035269, 0.00035151, 0.00035036,
       0.00034918, 0.00034795, 0.00034664, 0.00034524, 0.00034376,
       0.00034223, 0.00034068, 0.00033914, 0.00033766, 0.00033628,
       0.00033502, 0.00033388, 0.00033288, 0.00033199, 0.00033119,
       0.00033044, 0.0003297 , 0.00032895, 0.00032814, 0.00032727,
       0.00032632, 0.0003253 , 0.00032424, 0.00032317, 0.00032211,
       0.00032111, 0.0003202 , 0.00031939, 0.0003187 , 0.00031813,
       0.00031766, 0.00031726, 0.0003169 , 0.00031654, 0.00031616,
       0.00031574, 0.00031524, 0.00031467, 0.00031403, 0.00031336,
       0.00031266, 0.00031198, 0.00031136, 0.00031081, 0.00031037,
       0.00031003, 0.00030979, 0.00030965, 0.00030956, 0.00030951,
       0.00030945, 0.00030937, 0.00030923, 0.00030902, 0.00030873,
       0.00030839, 0.00030799, 0.00030759, 0.0003072 , 0.00030685,
       0.00030659, 0.00030642, 0.00030635, 0.00030638, 0.00030648,
       0.00030665, 0.00030683, 0.00030701, 0.00030716, 0.00030724,
       0.00030726, 0.00030719, 0.00030707, 0.0003069 , 0.00030671,
       0.00030654, 0.00030642, 0.00030638, 0.00030643, 0.00030659,
       0.00030683, 0.00030715, 0.00030752, 0.00030791, 0.00030829,
       0.00030863, 0.0003089 , 0.0003091 , 0.00030922, 0.00030927,
       0.00030928, 0.00030928, 0.0003093 , 0.00030938, 0.00030953,
       0.00030978, 0.00031013, 0.00031057, 0.00031108, 0.00031164,
       0.00031222, 0.00031278, 0.00031329, 0.00031373, 0.0003141 ,
       0.00031438, 0.00031459, 0.00031477, 0.00031493, 0.00031512,
       0.00031537, 0.00031571, 0.00031615, 0.00031669, 0.00031732,
       0.00031803, 0.00031878, 0.00031954, 0.00032027, 0.00032096,
       0.00032156, 0.00032208, 0.00032252, 0.00032289, 0.00032322,
       0.00032354, 0.0003239 , 0.00032433, 0.00032485, 0.00032548,
       0.00032621, 0.00032704, 0.00032795, 0.00032889, 0.00032984,
       0.00033076, 0.00033161, 0.00033238, 0.00033306, 0.00033365,
       0.00033417, 0.00033465, 0.00033514, 0.00033567, 0.00033627,
       0.00033698, 0.00033781, 0.00033875, 0.00033979, 0.0003409 ,
       0.00034205, 0.00034319, 0.0003443 , 0.00034532, 0.00034625,
       0.00034708, 0.00034781, 0.00034847, 0.0003491 , 0.00034974,
       0.00035044, 0.00035122, 0.00035212, 0.00035314, 0.00035429,
       0.00035554, 0.00035685, 0.00035819, 0.00035952, 0.00036079,
       0.00036196, 0.00036302, 0.00036396, 0.0003648 , 0.00036557,
       0.00036631, 0.00036707, 0.00036789, 0.00036882, 0.00036987,
       0.00037106, 0.00037237, 0.00037378, 0.00037524, 0.00037671,
       0.00037815, 0.0003795 , 0.00038072, 0.00038181, 0.00038277,
       0.0003836 , 0.00038436, 0.0003851 , 0.00038585, 0.00038669,
       0.00038763, 0.00038871, 0.00038993, 0.00039125, 0.00039266,
       0.0003941 , 0.00039551, 0.00039684, 0.00039804, 0.00039909,
       0.00039996, 0.00040067, 0.00040124, 0.00040173, 0.00040218,
       0.00040267, 0.00040323, 0.00040391, 0.00040471, 0.00040563,
       0.00040663, 0.00040767, 0.00040869, 0.00040963, 0.00041044,
       0.00041107, 0.00041148, 0.00041169, 0.00041187, 0.00041198,
       0.00041199, 0.00041198, 0.00041199, 0.00041208, 0.00041228,
       0.00041258, 0.00041297, 0.0004134 , 0.00041383, 0.00041419,
       0.00041442, 0.00041448, 0.00041432, 0.00041394, 0.00041334,
       0.00041257, 0.00041168, 0.00041073, 0.00040978, 0.0004089 ,
       0.00040812, 0.00040745, 0.00040689, 0.00040641, 0.00040597,
       0.0004055 , 0.00040497, 0.0004043 , 0.00040347, 0.00040245,
       0.00040125, 0.00039989, 0.00039841, 0.00039688, 0.00039535,
       0.00039388, 0.00039252, 0.00039128, 0.00039018, 0.00038919,
       0.00038828, 0.00038742, 0.00038654, 0.00038559, 0.00038454,
       0.00038336, 0.00038204, 0.00038058, 0.00037901, 0.00037739,
       0.00037575, 0.00037416, 0.00037266, 0.00037128, 0.00037003,
       0.00036892, 0.00036792, 0.00036699, 0.0003661 , 0.00036519,
       0.00036423, 0.00036317, 0.00036201, 0.00036073, 0.00035934,
       0.00035789, 0.0003564 , 0.00035493, 0.00035352, 0.0003522 ,
       0.00035101, 0.00034994, 0.00034899, 0.00034814, 0.00034736,
       0.00034659, 0.0003458 , 0.00034496, 0.00034404, 0.00034301,
       0.00034189, 0.00034068, 0.00033942, 0.00033815, 0.0003369 ,
       0.00033572, 0.00033463, 0.00033366, 0.0003328 , 0.00033205,
       0.00033137, 0.00033075, 0.00033014, 0.0003295 , 0.0003288 ,
       0.00032802, 0.00032716, 0.0003262 , 0.00032517, 0.00032411,
       0.00032304, 0.000322  , 0.00032103, 0.00032014, 0.00031937,
       0.0003187 , 0.00031812, 0.0003176 , 0.00031712, 0.00031665,
       0.00031614, 0.00031558, 0.00031493, 0.0003142 , 0.00031339,
       0.00031252, 0.00031162, 0.00031072, 0.00030986, 0.00030906,
       0.00030836])

In [4]:
man.config

                                                         value
key
spacecraft                                               JUICE
version                                                 latest
metakernel   /data/.cache/quick-spice-manager/kernels/juice...
kernels_dir     /data/.cache/quick-spice-manager/kernels/juice

In [5]:
man.cache_size

'1.4 GiB'

In [6]:
man.metakernels

['juice_crema_5_0',
 'juice_crema_5_0_v471_20260708_001',
 'juice_crema_5_0b23_1',
 'juice_crema_5_0b23_1_v471_20260708_001',
 'juice_crema_5_1_150la',
 'juice_crema_5_1_150la_v471_20260708_001',
 'juice_crema_5_1_150lb_23_1',
 'juice_crema_5_1_150lb_23_1_a3',
 'juice_crema_5_1_150lb_23_1_a3_2',
 'juice_crema_5_1_150lb_23_1_a3_2_v471_20260708_001',
 'juice_crema_5_1_150lb_23_1_a3_v471_20260708_001',
 'juice_crema_5_1_150lb_23_1_b2',
 'juice_crema_5_1_150lb_23_1_b2_v471_20260708_001',
 'juice_crema_5_1_150lb_23_1_v471_20260708_001',
 'juice_crema_5_2',
 'juice_crema_5_2_3G3to14C7_8E2lat',
 'juice_crema_5_2_3G3to14C7_8E2lat_V3',
 'juice_crema_5_2_3G3to14C7_8E2lat_V3_v471_20260708_001',
 'juice_crema_5_2_v471_20260708_001',
 'juice_crema_kallichore',
 'juice_crema_kallichore_v471_20260708_001',
 'juice_gco500_option_23',
 'juice_gco500_option_23_v471_20260708_001',
 'juice_gco500_option_32',
 'juice_gco500_option_32_v471_20260708_001',
 'juice_gco500_option_41',
 'juice_gco500_option_41_v471_20260708_001',
 'juice_gco500_option_50',
 'juice_gco500_option_50_v471_20260708_001',
 'juice_ops',
 'juice_ops_v471_20260709_002',
 'juice_plan',
 'juice_plan_v471_20260709_002',
 'juice_s003_7e1',
 'juice_s003_7e1_europa_flyby',
 'juice_s003_7e1_europa_flyby_v460_20251021_001',
 'juice_s003_7e1_v471_20260708_001',
 'juice_s007_pj12',
 'juice_s007_pj12_perijove_12',
 'juice_s007_pj12_perijove_12_v460_20251021_001',
 'juice_s007_pj12_v471_20260708_001',
 'juice_s008_orb17',
 'juice_s008_orb17_orbit_17',
 'juice_s008_orb17_orbit_17_v460_20251021_001',
 'juice_s008_orb17_v471_20260708_001',
 'juice_s008_ws',
 'juice_s008_ws_v471_20260708_001',
 'juice_s011_tr03',
 'juice_s011_tr03_v471_20260708_001']

In [7]:
import spiceypy

In [8]:
spiceypy.kclear()
spiceypy.furnsh(str(man.resolved_mk))